spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://tacomall-springboot-mysql-master:3306/tacomall?serverTimezone=Asia/Shanghai
        slave_1:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://tacomall-springboot-mysql-slave:3306/tacomall?serverTimezone=Asia/Shanghai