spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/tacomall?serverTimezone=Asia/Shanghai
  data:
    elasticsearch:
      cluster-name: es
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
wx:
  miniapp:
    configs:
      - appid:
        secret:
        token:
        aesKey:
        msgDataFormat: JSON