server:
  port: 4000
spring:
  profiles:
    active: dev
logging:
  level:
    com.baomidou: debug
wx:
  miniapp:
    configs:
      - appid:
        secret:
        token:
        aesKey:
        msgDataFormat: JSON
  oss:
    file:
      endpoint:
        keyid:
        keysecret:
        bucketname:
        filehost:


