server:
  port: 4000
spring:
  profiles:
    active: dev
logging:
  level:
    com.baomidou: debug
wx:
  miniapp:
    configs:
      - appid: wx9c2113eb137fdf6a
        secret: 6beabd0e7d4dbe2fbaa941eca08e3958
        token:
        aesKey:
        msgDataFormat: JSON
  oss:
    file:
      endpoint:
        keyid:
        keysecret:
        bucketname:
        filehost:


