spring:
  boot:
    admin:
      client:
        url: http://localhost:7030
        password: root
        username: 123456
        instance:
          prefer-ip: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
wx:
  miniapp:
    configs:
      - appid:
        secret:
        token:
        aesKey:
        msgDataFormat: JSON
oss:
  endPoint: oss-cn-shenzhen.aliyuncs.com
  accesskey: LTAI4Fickf14NieXeJSAQxcH
  accessSecret:
  bucket: mgteach-default
  expire: 3600
  host: mgteach-default.oss-cn-shenzhen.aliyuncs.com